In [51]:
import tensorflow as tf
import numpy as np

# 1 a)

In [2]:
#1a
x = tf.random_uniform([])
y = tf.random_uniform([])

In [3]:
out = tf.cond(tf.less(x,y), lambda: tf.add(x,y), lambda: tf.subtract(x,y))

In [4]:
#init = tf.global_variables_initializer()

In [5]:
with tf.Session() as sess:
    #sess.run(init)
    x_val = x.eval()
    y_val = y.eval()
    print(x_val)
    print(y_val)
    print(out.eval(feed_dict={x: x_val, y:y_val}))

0.392888
0.196607
0.196281


In [31]:
x_val + y_val

1.8041558

In [33]:
x_val - y_val

0.67620659

# 1b)

In [2]:
x = tf.random_uniform([])
y = tf.random_uniform([])

point_five = tf.constant(0.5,dtype=tf.float32)
minus_one = tf.constant(-1,dtype=tf.float32)
plus_one = tf.constant(1,dtype=tf.float32)

x_bern = tf.cond(tf.less(x,point_five),lambda: minus_one,lambda: plus_one)
y_bern = tf.cond(tf.less(y,point_five),lambda: minus_one,lambda: plus_one)

In [3]:
zero = tf.constant(0, dtype=tf.float32)

In [4]:
out = tf.case({tf.less(x_bern,y_bern): lambda: tf.add(x_bern,y_bern),
               tf.greater(x_bern,y_bern): lambda: tf.subtract(x_bern,y_bern)},
              default = lambda: zero,
              exclusive = True)

In [5]:
init = tf.global_variables_initializer()

In [6]:
with tf.Session() as sess:
    sess.run(init)
    x_val = x.eval()
    y_val = y.eval()
    x_bern_val = x_bern.eval(feed_dict={x: x_val})
    y_bern_val = y_bern.eval(feed_dict={y: y_val})
    print(x_val)
    print(y_val)
    print(x_bern_val)
    print(y_bern_val)
    print(out.eval(feed_dict={x: x_val, y:y_val}))

0.106822
0.325496
-1.0
-1.0
0.0


# 1c)

In [2]:
x = tf.Variable([[0, -2, -1], [0, 1, 2]])

In [3]:
y = tf.zeros_like(x)

In [4]:
out = tf.equal(x,y)

In [5]:
init = tf.global_variables_initializer()

In [6]:
with tf.Session() as sess:
    sess.run(init)
    x_val = x.eval()
    y_val = y.eval()
    print(x_val)
    print(y_val)
    print(out.eval(feed_dict={x: x_val, y:y_val}))    

[[ 0 -2 -1]
 [ 0  1  2]]
[[0 0 0]
 [0 0 0]]
[[ True False False]
 [ True False False]]


# 1 d)

In [10]:
x = tf.Variable([29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858])

val = tf.constant(30, tf.float32)

In [15]:
out = tf.where(tf.greater(x,val))
out_2 = tf.gather(x,out)

In [16]:
init = tf.global_variables_initializer()

In [18]:
with tf.Session() as sess:
    sess.run(init)
    x_val = x.eval()
    print(x_val)
    print(out.eval(feed_dict={x: x_val}))    
    print(out_2.eval(feed_dict={x: x_val}))    

[ 29.05088806  27.61298943  31.19073486  29.35532951  30.97266006
  26.67541885  38.08450317  20.74983215  34.94445419  34.45999146
  29.06485367  36.01657104  27.88236427  20.56035233  30.20379066
  29.51215172  33.71149445  28.59134293  36.05556488  28.66994858]
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


# 1e)

In [22]:
x = tf.range(start=1,limit=7,delta=1)
diag = tf.diag(x)

In [23]:
init = tf.global_variables_initializer()

In [24]:
with tf.Session() as sess:
    sess.run(init)
    print(diag.eval())

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


# 1f)

In [29]:
x = tf.random_normal([10,10])
out = tf.matrix_determinant(x)

In [30]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    x_val = x.eval()
    print(x_val)
    print(out.eval(feed_dict={x: x_val}))

[[-0.82636702 -1.40057087]
 [ 1.29999089  0.52061588]]
1.39051


In [31]:
0.5206*(-0.8264) - 1.2999*(-1.400)

1.38963616

# 1g)

In [32]:
x = tf.Variable([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
out = tf.unique(x)

In [36]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    x_val = x.eval()
    print(x_val)
    print(out.y.eval())

[ 5  2  3  5 10  6  2  3  4  2  1  1  0  9]
[ 5  2  3 10  6  4  1  0  9]


# 1h)

In [64]:
x = tf.random_normal(shape=[300],mean=2,stddev=1)
y = tf.random_normal(shape=[300],mean=2,stddev=1)

In [65]:
avg = tf.reduce_mean(tf.subtract(x,y))
zero = tf.constant(0,tf.float32)

In [66]:
out = tf.cond(tf.less(avg,zero),
              lambda: tf.reduce_mean(tf.square(tf.subtract(x,y))),
              lambda: tf.reduce_sum(tf.abs(tf.subtract(x,y))))

In [72]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    x_val = x.eval()
    y_val = y.eval()
    #print(x_val)
    #print(y_val)
    print(avg.eval(feed_dict={x: x_val, y:y_val}))
    print(out.eval(feed_dict={x: x_val, y:y_val}))

-0.0277516
1.97634
