In [1]:
import numpy as np

# Set up paramaters

In [2]:
l_1 = 1
l_2 = 1

# Initial params

In [111]:
theta_1_phi = 0
theta_1_z = 0
theta_1_omega = 0
theta_2_phi = 0
theta_2_z = 0

# Forward Kinematics

In [112]:
x = l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
y = l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
z = l_1 * np.sin(theta_1_phi) + l_2 * np.sin(theta_2_phi + theta_1_phi)

theta_x_phi = theta_1_phi + theta_2_phi
theta_x_z = theta_2_z + theta_1_z + theta_1_omega

# Creating this into a function

In [189]:
def forward_kinematics(theta_1_phi, theta_1_z, theta_1_omega, theta_2_phi, theta_2_z):
    x = l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
    y = l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
    z = l_1 * np.sin(theta_1_phi) + l_2 * np.sin(theta_2_phi + theta_1_phi)

    theta_x_phi = theta_1_phi + theta_2_phi
    theta_x_z = theta_2_z + theta_1_z + theta_1_omega
    return [x,y,z,theta_x_phi,theta_x_z]


def forward_kinematics_vec(vec):
    theta_1_phi = float(vec[0])
    theta_1_z = float(vec[1])
    theta_1_omega = float(vec[2])
    theta_2_phi = float(vec[3])
    theta_2_z = float(vec[4])
    
    x = l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
    y = l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
    z = l_1 * np.sin(theta_1_phi) + l_2 * np.sin(theta_2_phi + theta_1_phi)

    theta_x_phi = theta_1_phi + theta_2_phi
    theta_x_z = theta_2_z + theta_1_z + theta_1_omega
    return np.transpose(np.matrix([x,y,z,theta_x_phi,theta_x_z]))

In [178]:
forward_kinematics(-0.25,0,0,0.5,0)

[1.9378248434212895, 0.0, 0.0, 0.25, 0]

In [44]:
print x
print y
print z
print theta_x_phi
print theta_x_z

2.0
0.0
0.0
0
0


# Calculate the Jacobian of the above transformation

In [70]:
J = np.matrix([
                [ -1 * l_1 * np.sin(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ]
        ,
                [ -1 * l_1 * np.sin(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ]
        ,
                [  1 * l_1 * np.cos(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ,  0
                ,  1 * l_1 * np.sin(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ]
        ,
                [ 1
                , 0
                , 0
                , 1
                , 0
                ]
        ,
                [ 0
                , 1
                , 1
                , 0
                , 1
                ]
    ])
    


In [157]:
def Jacobian_vec(vec):
    theta_1_phi = float(vec[0])
    theta_1_z = float(vec[1])
    theta_1_omega = float(vec[2])
    theta_2_phi = float(vec[3])
    theta_2_z = float(vec[4])
    
    J = np.matrix([
                [ -1 * l_1 * np.sin(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ]
        ,
                [ -1 * l_1 * np.sin(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ]
        ,
                [  1 * l_1 * np.cos(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ,  0
                ,  1 * l_1 * np.sin(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ]
        ,
                [ 1
                , 0
                , 0
                , 1
                , 0
                ]
        ,
                [ 0
                , 1
                , 1
                , 0
                , 1
                ]
    ])
    
    return J



def Jacobian(theta_1_phi, theta_1_z, theta_1_omega, theta_2_phi, theta_2_z):
    J = np.matrix([
                [ -1 * l_1 * np.sin(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ]
        ,
                [ -1 * l_1 * np.sin(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                , -1 * l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ]
        ,
                [  1 * l_1 * np.cos(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ,  0
                ,  1 * l_1 * np.sin(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ]
        ,
                [ 1
                , 0
                , 0
                , 1
                , 0
                ]
        ,
                [ 0
                , 1
                , 1
                , 0
                , 1
                ]
    ])
    
    return J

In [122]:
Jacobian(0,0,0,0,0)

matrix([[-0., -0., -0., -0., -0.],
        [-0.,  2.,  1., -0.,  1.],
        [ 2.,  0.,  0.,  1.,  0.],
        [ 1.,  0.,  0.,  1.,  0.],
        [ 0.,  1.,  1.,  0.,  1.]])

# Get desired new coordinates from first order taylor series expansion

In [113]:
x_new = 1.9378248434212895
y_new = 0
z_new = 0
theta_x_phi_new = 0.25
theta_z_phi_new = 0

In [114]:
new_coords = np.matrix(
[
         [x_new]
        ,[y_new]
        ,[z_new]
        ,[theta_x_phi_new]
        ,[theta_z_phi_new]
    ])

old_coords = np.matrix(
[
         [x]
        ,[y]
        ,[z]
        ,[theta_x_phi]
        ,[theta_x_z]
    ])

delta_position = new_coords - old_coords


# Calculate pseudo inverse if matrix rank is < 5. This gives a least squares solution

In [115]:
delta_coords = np.dot(
                 np.linalg.pinv(Jacobian(0,0,0,0,0))
                ,delta_position )

In [116]:
delta_coords

matrix([[ -2.50000000e-01],
        [  2.04604235e-17],
        [ -1.42425567e-17],
        [  5.00000000e-01],
        [ -1.42425567e-17]])

# Check if this works

In [117]:
theta_1_phi += delta_coords[0]
theta_1_z += delta_coords[1]
theta_1_omega += delta_coords[2]
theta_2_phi += delta_coords[3]
theta_2_z += delta_coords[4]

In [118]:
x = l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
y = l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
z = l_1 * np.sin(theta_1_phi) + l_2 * np.sin(theta_2_phi + theta_1_phi)

theta_x_phi = theta_1_phi + theta_2_phi
theta_x_z = theta_2_z + theta_1_z + theta_1_omega

In [119]:
print x
print y
print z
print theta_x_phi
print theta_x_z

[[ 1.93782484]]
[[  1.20491367e-17]]
[[ -1.11022302e-16]]
[[ 0.25]]
[[ -8.02468996e-18]]


# Get function to calculate new coordinates from old position

In [205]:
def get_new_rotations(new_vec, old_rotations):
    J = Jacobian_vec(old_rotations)
    old_vec = forward_kinematics_vec(old_rotations)
    delta_position = new_vec - old_vec
    delta_coords = np.dot(
                 np.linalg.pinv(J)
                ,delta_position )
    return delta_coords + old_rotations
    

# Testing if this works

In [190]:
old_rotations = np.matrix(
[
         [0]
        ,[0]
        ,[0]
        ,[0]
        ,[0]
    ])

new_rotations = np.matrix(
[
         [-0.25]
        ,[0]
        ,[0]
        ,[0.5]
        ,[0]
    ])

new_vec = forward_kinematics_vec(new_rotations)

In [206]:
get_new_rotations(new_vec,old_rotations)

matrix([[ -2.50000000e-01],
        [  2.04604235e-17],
        [ -1.42425567e-17],
        [  5.00000000e-01],
        [ -1.42425567e-17]])

# Applying this to random rotations

# Start here

In [343]:
old_rotations = np.transpose(np.matrix(np.random.uniform(high=3.14,low=0,size=5)))

new_rotations = old_rotations + np.transpose(np.matrix(np.random.uniform(high=1,low=-1,size=5)))

old_rotations

matrix([[ 0.44945321],
        [ 0.25626182],
        [ 2.17727154],
        [ 2.85533886],
        [ 2.445061  ]])

# Get original position

In [344]:
forward_kinematics_vec(old_rotations)

matrix([[ 0.70802934],
        [ 1.20140844],
        [ 0.27199718],
        [ 3.30479206],
        [ 4.87859436]])

## original position above

In [345]:
new_rotations

matrix([[ 0.28066698],
        [ 0.87590159],
        [ 3.06276175],
        [ 3.3323094 ],
        [ 2.67049486]])

# Get new position

In [346]:
new_vec = forward_kinematics_vec(new_rotations)

In [347]:
new_vec

matrix([[-0.22877344],
        [ 0.45275872],
        [-0.17712295],
        [ 3.61297638],
        [ 6.6091582 ]])

## new position above

# Now loop through

In [348]:
old_rotations = get_new_rotations(new_vec,old_rotations)
error = np.linalg.norm(forward_kinematics_vec(old_rotations) - new_vec)
error

1.2118777484398331

In [349]:
cnt = 0
error = 1

while (cnt < 10 and error > 0.01): 

    old_rotations = get_new_rotations(new_vec,old_rotations)
    error = np.linalg.norm(forward_kinematics_vec(old_rotations) - new_vec)

# Final position below:

In [350]:
forward_kinematics_vec(old_rotations)

matrix([[-0.22809781],
        [ 0.45357287],
        [-0.18181101],
        [ 3.61282377],
        [ 6.60971772]])

In [351]:
error = np.linalg.norm(forward_kinematics_vec(old_rotations) - new_vec)
error

0.0048408227422841879