In [1]:
import numpy as np

# Set up paramaters

In [2]:
l_1 = 1
l_2 = 1

# Initial params

In [40]:
theta_1_phi = 0
theta_1_z = 0
theta_1_omega = 0
theta_2_phi = 0
theta_2_z = 0

# Forward Kinematics

In [41]:
x = l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
y = l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
z = l_1 * np.sin(theta_1_phi) + l_2 * np.sin(theta_2_phi + theta_1_phi)

theta_x_phi = theta_1_phi + theta_2_phi
theta_x_z = theta_2_z + theta_1_z + theta_1_omega

# Creating this into a function

In [42]:
def forward_kinematics(theta_1_phi, theta_1_z, theta_1_omega, theta_2_phi, theta_2_z):
    x = l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
    y = l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
    z = l_1 * np.sin(theta_1_phi) + l_2 * np.sin(theta_2_phi + theta_1_phi)

    theta_x_phi = theta_1_phi + theta_2_phi
    theta_x_z = theta_2_z + theta_1_z + theta_1_omega
    return [x,y,z,theta_x_phi,theta_x_z]

In [43]:
forward_kinematics(-0.025,0,0,0.05,0)

[1.9993750325514053, 0.0, 0.0, 0.025, 0]

In [44]:
print x
print y
print z
print theta_x_phi
print theta_x_z

2.0
0.0
0.0
0
0


# Calculate the Jacobian of the above transformation

In [70]:
J = np.matrix([
                [ -1 * l_1 * np.sin(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ]
        ,
                [ -1 * l_1 * np.sin(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ]
        ,
                [  1 * l_1 * np.cos(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ,  0
                ,  1 * l_1 * np.sin(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ]
        ,
                [ 1
                , 0
                , 0
                , 1
                , 0
                ]
        ,
                [ 0
                , 1
                , 1
                , 0
                , 1
                ]
    ])
    


In [68]:
def Jacobian(theta_1_phi, theta_1_z, theta_1_omega, theta_2_phi, theta_2_z):
    J = np.matrix([
                [ -1 * l_1 * np.sin(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                , -1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) - l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ]
        ,
                [ -1 * l_1 * np.sin(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega) 
                ,  1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) - l_2 * np.sin(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
                ,  1 * l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
                ]
        ,
                [  1 * l_1 * np.cos(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ,  0
                ,  1 * l_1 * np.sin(theta_1_phi) + l_2 * np.cos(theta_2_phi + theta_1_phi) 
                ,  0
                ]
        ,
                [ 1
                , 0
                , 0
                , 1
                , 0
                ]
        ,
                [ 0
                , 1
                , 1
                , 0
                , 1
                ]
    ])
    
    return J

In [72]:
Jacobian(0,0,0,0,0)

matrix([[-0., -0.,  1.,  1.,  1.],
        [-0.,  2.,  1.,  0.,  1.],
        [ 2.,  0.,  0.,  1.,  0.],
        [ 1.,  0.,  0.,  1.,  0.],
        [ 0.,  1.,  1.,  0.,  1.]])

# Get desired new coordinates from first order taylor series expansion

In [62]:
x_new = 1.9994
y_new = 0
z_new = 0
theta_x_phi_new = 0.025
theta_z_phi_new = 0

In [63]:
new_coords = np.matrix(
[
         [x_new]
        ,[y_new]
        ,[z_new]
        ,[theta_x_phi_new]
        ,[theta_z_phi_new]
    ])

old_coords = np.matrix(
[
         [x]
        ,[y]
        ,[z]
        ,[theta_x_phi]
        ,[theta_x_z]
    ])

delta_position = new_coords - old_coords


# Calculate pseudo inverse if matrix rank is < 5. This gives a least squares solution

In [64]:
delta_coords = np.dot(
                 np.linalg.pinv(Jacobian)
                ,delta_position )

In [65]:
delta_coords

matrix([[-0.0112],
        [ 0.0138],
        [-0.0115],
        [ 0.027 ],
        [-0.0115]])

# Check if this works

In [27]:
theta_1_phi += delta_coords[0]
theta_1_z += delta_coords[1]
theta_1_omega += delta_coords[2]
theta_2_phi += delta_coords[3]
theta_2_z += delta_coords[4]

In [28]:
x = l_1 * np.cos(theta_1_phi) * np.cos(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.cos(theta_2_z + theta_1_z + theta_1_omega)
y = l_1 * np.cos(theta_1_phi) * np.sin(theta_1_z) + l_2 * np.cos(theta_2_phi + theta_1_phi) * np.sin(theta_2_z + theta_1_z + theta_1_omega)
z = l_1 * np.sin(theta_1_phi) + l_2 * np.sin(theta_2_phi + theta_1_phi)

theta_x_phi = theta_1_phi + theta_2_phi
theta_x_z = theta_2_z + theta_1_z + theta_1_omega

In [29]:
print x
print y
print z
print theta_x_phi
print theta_x_z

[[ 1.99870066]]
[[ 0.00927253]]
[[ 0.00926936]]
[[ 0.03145455]]
[[-0.01854545]]


# Not quite what we want but not sure if such a configuration exists.

## Next will wrap this code in functions and apply to configurations that do exist so that we can scope for bugs

In [79]:
delta_theta = np.matrix(
[
         [-0.025]
        ,[0]
        ,[0]
        ,[0.05]
        ,[0]
    ])

In [88]:
delta_pos = np.dot(
Jacobian(0,0,0,0,0),
delta_theta
)

In [89]:
delta_pos

matrix([[ 0.05 ],
        [ 0.   ],
        [ 0.   ],
        [ 0.025],
        [ 0.   ]])

In [93]:
forward_kinematics(-0.025,0,0,0.025,0)

[1.9996875162757026, 0.0, -0.024997395914712332, 0.0, 0]

In [96]:
np.linalg.inv(Jacobian(-0.025,0,0,0.025,0))

matrix([[  0.00000000e+00,   0.00000000e+00,   9.75909753e-01,
          -9.51514551e-01,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          -4.00062507e+00,   0.00000000e+00],
        [ -3.61114116e+16,  -3.61114116e+16,  -3.43495212e+16,
           6.95909999e+16,   7.22115389e+16],
        [  0.00000000e+00,   0.00000000e+00,  -9.75909753e-01,
           1.95151455e+00,   0.00000000e+00],
        [  3.61114116e+16,   3.61114116e+16,   3.43495212e+16,
          -6.95909999e+16,  -7.22115389e+16]])